# Generated by Django 5.0.8 on 2024-10-03 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_appeal_details_appeal_details_of_appeal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.registers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
