# Generated by Django 5.0.8 on 2024-10-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_grievance_user_alter_registers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='user',
        ),
    ]
