# Generated by Django 5.0.8 on 2024-10-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_registers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registers',
            name='id',
        ),
        migrations.AddField(
            model_name='registers',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
