# Generated by Django 5.0.8 on 2024-10-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_registers_id_registers_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registers',
            name='user_id',
        ),
        migrations.AddField(
            model_name='registers',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
