# Generated by Django 5.0.8 on 2024-10-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_registers_user_id_registers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
