# Generated by Django 5.0.8 on 2024-10-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_registers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
