# Generated by Django 5.0.8 on 2024-10-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_appeal_details_appeal_details_of_appeal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Conference', 'Conference'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('date_of_event', models.DateField()),
            ],
        ),
    ]
