# Generated by Django 5.0.8 on 2024-10-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_of_event',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
    ]
