# Generated by Django 5.0.8 on 2024-10-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_date_of_event_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='appealresolution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
