# Generated by Django 5.0.8 on 2024-10-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_appeal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='user',
        ),
    ]
