# Generated by Django 5.0.8 on 2024-10-08 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_appeal_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='name',
        ),
        migrations.AddField(
            model_name='grievance',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='grievance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grievance',
            name='complaint_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grievance',
            name='type_of_grievance',
            field=models.CharField(max_length=50),
        ),
    ]
