# Generated by Django 5.0.8 on 2024-10-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_grievance_name_grievance_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='user',
        ),
        migrations.AddField(
            model_name='grievance',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='complaint_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='type_of_grievance',
            field=models.CharField(choices=[('academic', 'Academic'), ('administrative', 'Administrative'), ('others', 'Others')], max_length=50),
        ),
    ]
