# Generated by Django 5.0.8 on 2024-10-16 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_grievance_status_remove_grievance_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='accounts.registers'),
        ),
    ]
