# Generated by Django 5.0.8 on 2024-10-16 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_grievance_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='accounts.registers'),
        ),
    ]
