# Generated by Django 5.0.8 on 2024-10-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_appeal_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
