# Generated by Django 5.0.8 on 2024-10-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_grievance_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='assigned_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
