# Generated by Django 5.0.8 on 2024-10-18 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_grievance_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.registers'),
        ),
    ]
