# Generated by Django 5.0.8 on 2024-10-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_grievance_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='facultyresolution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
